server:
  port: 8081
spring:
  spring:
    jackson:
      serialization:
        fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update